### ISSUE TITLE
import  rpc-spring-boot-starter-1.0.0-SNAPSHOT to example

### ISSUE THREAD

**Issue by meolachina** [2YSP/rpc-example#1]
I  mvn-installed rpc-spring-boot-starter-1.0.0-SNAPSHOT.jar  successfully, but i can't install this jar to my local mvn repo. I tried this under the jar path:

mvn install:install-file -DgroupId=cn.sp.rpc -DartifactId=rpc-spring-boot-starter -Dversion=1.0.0-SNAPSHOT -Dpackaging=jar -Dfile=jardirectory\rpc-spring-boot-starter-1.0.0-SNAPSHOT.jar

and errors like : no pom file. so how to compile the example successfully

**Comment by 2YSP** [comment]
Sorry, I only saw your issue now. I will upload a jar package to Maven's central warehouse later so that you can easily reference it.

**Comment by 2YSP** [comment]
> I mvn-installed rpc-spring-boot-starter-1.0.0-SNAPSHOT.jar successfully, but i can't install this jar to my local mvn repo. I tried this under the jar path:
> 
> mvn install:install-file -DgroupId=cn.sp.rpc -DartifactId=rpc-spring-boot-starter -Dversion=1.0.0-SNAPSHOT -Dpackaging=jar -Dfile=jardirectory\rpc-spring-boot-starter-1.0.0-SNAPSHOT.jar
> 
> and errors like : no pom file. so how to compile the example successfully

Sorry, I only saw your issue now. I will upload a jar package to Maven's central warehouse later so that you can easily reference it.

**Comment by 2YSP** [comment]
> I mvn-installed rpc-spring-boot-starter-1.0.0-SNAPSHOT.jar successfully, but i can't install this jar to my local mvn repo. I tried this under the jar path:
> 
> mvn install:install-file -DgroupId=cn.sp.rpc -DartifactId=rpc-spring-boot-starter -Dversion=1.0.0-SNAPSHOT -Dpackaging=jar -Dfile=jardirectory\rpc-spring-boot-starter-1.0.0-SNAPSHOT.jar
> 
> and errors like : no pom file. so how to compile the example successfully

     <dependency>
            <groupId>io.github.2ysp</groupId>
            <artifactId>ship-rpc-spring-boot-starter</artifactId>
            <version>1.0.0-RELEASE</version>
        </dependency>
